In [1]:
import pandas as pd
df = pd.read_csv('train.csv')

In [2]:
df.head()

ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0       1     39353   85475         117961         118300         123472   
1       1     17183    1540         117961         118343         123125   
2       1     36724   14457         118219         118220         117884   
3       1     36135    5396         117961         118343         119993   
4       1     42680    5905         117929         117930         119569   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117905            117906       290919     117908  
1      118536            118536       308574     118539  
2      117879            267952        19721     117880  
3      118321            240983       290919     118322  
4      119323            123932        19793     119325

In [2]:
n_features = 7

In [3]:
from scipy import sparse
from sklearn.model_selection import cross_val_score

l = []
X = df.values[:, 1:]
y = df.values[:, 0].ravel()
X_binarized = [lb.fit_transform(c) for c in X.T]
good_features = []
results = []
n = X.shape[1]
n_feature = None
if n == 0:
    raise ValueError("Array X cannot be empty.")
if n_feature is None:
    n_feature = n
print n_feature,n, (n_feature <= 0)
if (n_feature > n) or (n_feature <= 0):
    raise ValueError("n_feature cannot be non-positive or larger that the number of features in the input array X. Received %s." % str(n_features))

if 0 < n_features < 1:
    n_features = np.ceil(n * n_features)
    
last_score, score = None, 0
while len(good_features) < n_features:
    scores = []
    for f in range(X.shape[1]):
        if f not in good_features:
            curr_features = list(good_features) + [f]
            X_sub = sparse.hstack([X_binarized[i] for i in curr_features]).tocsr()
            score = cross_val_score(clf, X_sub, y, scoring=scoring).mean()
            scores.append((f, score))
    best_f, best_score = max(scores, key = lambda x:x[1])
    
    if last_score is not None and best_score <= last_score:
        break
    
    good_features.append(best_f)
    results.append((best_f, best_score))
    print results

    last_score = best_score

best_features = map(lambda x:x[0], results)
best_score = results[-1][1]
print best_features
print best_score

NameError: name 'lb' is not defined

In [23]:
X_sub = sparse.hstack([X_binarized[i] for i in range(9)]).tocsr()

cross_val_score(clf, X_sub, y, scoring=scoring).mean()

0.85848037999070825

In [13]:
best_features

[1, 0, 6, 8, 7, 3, 4]

In [16]:
df.columns[1:][best_features]

Index([u'MGR_ID', u'RESOURCE', u'ROLE_FAMILY_DESC', u'ROLE_CODE',
       u'ROLE_FAMILY', u'ROLE_ROLLUP_2', u'ROLE_DEPTNAME'],
      dtype='object')

In [357]:
best_features

[1, 0, 6, 8, 4, 3, 7]

In [358]:
best_score

0.85718661926958095

In [22]:
from itertools import chain
def generate_combs(s, k):
    if k == 0 or k > len(s):
        yield []
        return 
    
    for i in range(len(s)-k+1):
        for c in generate_combs(s[i+1:], k-1):
            yield [s[i]] + c
                    
                    
    

In [23]:
list(generate_combs(range(5), 3))

[[0, 1, 2],
 [0, 1, 3],
 [0, 1, 4],
 [0, 2, 3],
 [0, 2, 4],
 [0, 3, 4],
 [1, 2, 3],
 [1, 2, 4],
 [1, 3, 4],
 [2, 3, 4]]

In [47]:
import numpy as np
def concatination_features(data, degree=2):
    """
    Create new features by concatinating existing features
    from data. This is similiar to polinomial feature generation
    but can be used with categorical data as well.
    
    Parameters:
    -----------
    data: numpy array, contains data with features to be concatinated
    
    degree: int, number of features to concatinate to generate each new
    feature. For example, if there are three features 'a', 'b', and 'c'
    and degree=2, generated features are 'ab', 'ac', 'bc'.
    
    """
    m, n = data.shape
    
    feature_combs = generate_combs(range(n), degree)
    
    return np.vstack(
                    [np.array([hash(tuple(row)) 
                               for row in data[:, comb].tolist()])]
                                   for comb in feature_combs
    ).T

In [38]:
data = train.as_matrix()
m, n = data.shape

feature_combs = generate_combs(range(n), k=1)


In [39]:
np.vstack(
                [np.array([hash(tuple(row)) 
                           for row in data[:, comb].tolist()])]
                               for comb in feature_combs
)

array([[3430019387558, 3430019387558, 3430019387558, ..., 3430019387558,
        3430019387558, 3430019387558],
       [3461067480702, 3413361337584, 3463446487839, ..., 3464734491703,
        3501264601293, 3436148405945],
       [3480485538956, 3428486382959, 3436043405630, ..., 3417863351090,
        3444525431076, 3456729467688],
       ...,
       [3513076636729, 3512698635595, 3162321584467, ..., 3540904720213,
        3153589558271, 3509104624813],
       [3155496563992, 3203887709165, 3414907342222, ..., 3512630635391,
        3154380560644, 3414907342222],
       [3513078636735, 3512701635604, 3512842636027, ..., 3518862654087,
        3508060621681, 3512668635505]])

In [7]:
train = pd.read_csv('train.csv')

In [27]:
data = train.iloc[:10, :3].as_matrix()

In [12]:
data

array([[    1, 39353, 85475],
       [    1, 17183,  1540],
       [    1, 36724, 14457],
       [    1, 36135,  5396],
       [    1, 42680,  5905],
       [    0, 45333, 14561],
       [    1, 25993, 17227],
       [    1, 19666,  4209],
       [    1, 31246,   783],
       [    1, 78766, 56683]])

In [13]:
concatination_features(data, degree=1).shape

(3, 10)

In [41]:
concatination_features(train.as_matrix(), degree=2)

array([[3713081593804632581, 3713081613378849631, 3713081599014825406,
        ..., 3713081598711718406, 3713081708815336156,
        3713081638602764656],
       [3713081688086064931, 3713081632495158606, 3713081638629827781,
        ..., 3713081618499192881, 3713081576308863531,
        3713081589658561831],
       [3713081652919157781, 3713081652919157781, 3713081652639866331,
        ..., 3713081652919157781, 3713081652634453706,
        3713081652872609206],
       ...,
       [3802992883545139856, 3802583751228827281, 3423292086759634856,
        ..., 3833117828409294481, 3413839132170712606,
        3798693361501076906],
       [3802993053234181181, 3802584108805237706, 3423292121901643931,
        ..., 3833117821922804681, 3413839515002431281,
        3798693254492398131],
       [3415903829100288256, 3468288415453038256, 3696722415271732506,
        ..., 3802510451410774931, 3414695830855374706,
        3696722416048985456]])

In [207]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
X_train = train.iloc[:, 1:]
y_train = train.iloc[:, 0]
X_test = test.iloc[:, 1:]


In [159]:
def make_poli_features(data, max_degree):
    data_matrix = data.as_matrix()
    data_poli_feature = [data_matrix]
    for d in range(2, max_degree+1):
        data_poli_feature.append(concatination_features(data_matrix, degree=d))

    return np.hstack(data_poli_feature)    

In [160]:
def OneHotEncoder1(data, keymap=None):
    """
    OneHotEncoder takes data matrix with categorical columns and
    converts it to a sparse binary matrix.

    Returns sparse binary matrix and keymap mapping categories to indicies.
    If a keymap is supplied on input it will be used instead of creating one
    and any categories appearing in the data that are not in the keymap are
    ignored
    """
    if keymap is None:
      keymap = []
      for col in data.T:
           uniques = set(list(col))
           keymap.append(dict((key, i) for i, key in enumerate(uniques)))
    total_pts = data.shape[0]
    outdat = []
    for i, col in enumerate(data.T):
      km = keymap[i]
      num_labels = len(km)
      spmat = sparse.lil_matrix((total_pts, num_labels))
      for j, val in enumerate(col):
           if val in km:
                spmat[j, km[val]] = 1
      outdat.append(spmat)
    outdat = sparse.hstack(outdat).tocsr()
    return outdat, keymap


In [208]:
from sklearn.preprocessing import OneHotEncoder
max_degree = 2
X_train_poli = make_poli_features(X_train, max_degree)
X_test_poli = make_poli_features(X_test, max_degree)



In [209]:
def one_hot_endcode(X_train, X_test):
    #ohe = OneHotEncoder()

    X_total = np.vstack([X_train, X_test])

    #X_total_ohe, _ = ohe.fit_transform(X_total)
    X_total_ohe, _ = OneHotEncoder1(X_total)

    n_train = X_train.shape[0]

    X_train_ohe = X_total_ohe[:n_train,]

    X_test_ohe = X_total_ohe[n_train:,]
    
    return X_train_ohe, X_test_ohe

X_train_ohe, X_test_ohe = one_hot_endcode(X_train_poli, X_test_poli)


In [198]:
GridSearchCV?

In [210]:
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()

gs = GridSearchCV(clf, param_grid={'C': np.logspace(-1, 1, 10)}, scoring=scoring)

In [211]:
X_train_ohe.shape

(32769, 372637)

In [212]:
train.shape

(32769, 10)

In [213]:
y_train.shape

(32769,)

In [218]:
gs.fit(X_train_ohe, y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': array([ 0.1    ,  0.16681,  0.27826,  0.46416,  0.77426,  1.29155,
        2.15443,  3.59381,  5.99484, 10.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=<function scoring at 0x7fac25b74500>, verbose=0)

In [219]:
gs.best_params_

{'C': 0.2782559402207124}

In [222]:
gs.best_index_

2

In [184]:
X_train_ohe.shape

(196614, 372637)

In [217]:
from sklearn.metrics import roc_auc_score

In [220]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

def scoring(estimator, X, y):
    y_pred = estimator.predict_proba(X)
    return roc_auc_score(y, y_pred[:, 1])

#clf = LogisticRegression(C=3)
clf = gs.best_estimator_
cross_val_score(clf, X_train_ohe, y_train, n_jobs=4)

array([0.95294764, 0.94918978, 0.94964292])

In [167]:
def make_submission_file(y_test_pred, filename=None):
    submit_data = pd.DataFrame(columns=['ID', 'ACTION'])
    submit_data['ID'] = xrange(1, len(y_test_pred)+1)
    submit_data['ACTION'] = y_test_pred
    if not filename:
        filename = 'submit.csv'
    submit_data.to_csv(filename, index=False)

In [192]:
from scipy.sparse import vstack

n_stack = 2
X_train_ohe_double = vstack([X_train_ohe for _ in range(n_stack)])
y_train_double = np.vstack([y_train.reshape(-1, 1) for _ in range(n_stack)]).ravel()

# Shuffle train data

n_train = X_train_ohe_double.shape[0]
shuffle_index = np.random.permutation(n_train)
X_train_ohe = X_train_ohe_double[shuffle_index]
y_train = y_train_double[shuffle_index]


In [187]:
X_train_ohe.shape

(196614, 372637)

In [223]:
clf.fit(X_train_ohe, y_train)
y_test_pred = clf.predict_proba(X_test_ohe)

In [224]:
make_submission_file(y_test_pred, 'submit/submit_poli2_gs.csv')

In [225]:
y_test_pred

array([[0.15683261, 0.84316739],
       [0.00428315, 0.99571685],
       [0.00507291, 0.99492709],
       ...,
       [0.00392877, 0.99607123],
       [0.14802298, 0.85197702],
       [0.00343923, 0.99656077]])

In [194]:
y_test_pred

array([[1.84449983e-03, 9.98155500e-01],
       [7.09500411e-05, 9.99929050e-01],
       [2.08776809e-05, 9.99979122e-01],
       ...,
       [9.53285867e-06, 9.99990467e-01],
       [5.69082323e-02, 9.43091768e-01],
       [3.69419017e-06, 9.99996306e-01]])

In [226]:
##TODO
## Try RF and XGB with GridSearch 