In [2]:
import pandas as pd
df = pd.read_csv('train.csv')

In [3]:
df.head()

ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0       1     39353   85475         117961         118300         123472   
1       1     17183    1540         117961         118343         123125   
2       1     36724   14457         118219         118220         117884   
3       1     36135    5396         117961         118343         119993   
4       1     42680    5905         117929         117930         119569   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117905            117906       290919     117908  
1      118536            118536       308574     118539  
2      117879            267952        19721     117880  
3      118321            240983       290919     118322  
4      119323            123932        19793     119325

In [4]:
df.describe()

ACTION       RESOURCE         MGR_ID  ROLE_ROLLUP_1  \
count  32769.000000   32769.000000   32769.000000   32769.000000   
mean       0.942110   42923.916171   25988.957979  116952.627788   
std        0.233539   34173.892702   35928.031650   10875.563591   
min        0.000000       0.000000      25.000000    4292.000000   
25%        1.000000   20299.000000    4566.000000  117961.000000   
50%        1.000000   35376.000000   13545.000000  117961.000000   
75%        1.000000   74189.000000   42034.000000  117961.000000   
max        1.000000  312153.000000  311696.000000  311178.000000   

       ROLE_ROLLUP_2  ROLE_DEPTNAME     ROLE_TITLE  ROLE_FAMILY_DESC  \
count   32769.000000   32769.000000   32769.000000      32769.000000   
mean   118301.823156  118912.779914  125916.152644     170178.369648   
std      4551.588572   18961.322917   31036.465825      69509.462130   
min     23779.000000    4674.000000  117879.000000       4673.000000   
25%    118102.000000  118395.000000  118274.000000     117906.000000   
50%    118300.000000  118921.000000  118568.000000     128696.000000   
75%    118386.000000  120535.000000  120006.000000     235280.000000   
max    286791.000000  286792.000000  311867.000000     311867.000000   

         ROLE_FAMILY      ROLE_CODE  
count   32769.000000   32769.000000  
mean   183703.408893  119789.430132  
std    100488.407413    5784.275516  
min      3130.000000  117880.000000  
25%    118363.000000  118232.000000  
50%    119006.000000  118570.000000  
75%    290919.000000  119348.000000  
max    308574.000000  270691.000000

In [21]:
for c in df.columns:
    print c, len(np.unique(df[c]))

ACTION 2
RESOURCE 7518
MGR_ID 4243
ROLE_ROLLUP_1 128
ROLE_ROLLUP_2 177
ROLE_DEPTNAME 449
ROLE_TITLE 343
ROLE_FAMILY_DESC 2358
ROLE_FAMILY 67
ROLE_CODE 343


In [5]:
import numpy as np
from sklearn import preprocessing

lb = preprocessing.LabelBinarizer(sparse_output=True)

lb.fit(np.array([[0, 1, 1], [1, 0, 0]]))

lb.classes_

lb.transform([0, 1, 2, 1])



<4x3 sparse matrix of type '<type 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [6]:
df.head()


ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0       1     39353   85475         117961         118300         123472   
1       1     17183    1540         117961         118343         123125   
2       1     36724   14457         118219         118220         117884   
3       1     36135    5396         117961         118343         119993   
4       1     42680    5905         117929         117930         119569   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117905            117906       290919     117908  
1      118536            118536       308574     118539  
2      117879            267952        19721     117880  
3      118321            240983       290919     118322  
4      119323            123932        19793     119325

In [30]:
lb.fit_transform(df.ROLE_FAMILY).shapeb

(32769, 67)

In [9]:
l = []
for c in df.columns:
    print c
    col_b = lb.fit_transform(df[c])
    #col_b = pd.DataFrame(col_b, columns=map(lambda x: c + '_'+str(x), range(col_b.shape[1])))
    #
    #df1 = pd.concat([df1, col_b], axis=1)
    print col_b.shape
    l.append(col_b)



ACTION
(32769, 1)
RESOURCE
(32769, 7518)
MGR_ID
(32769, 4243)
ROLE_ROLLUP_1
(32769, 128)
ROLE_ROLLUP_2
(32769, 177)
ROLE_DEPTNAME
(32769, 449)
ROLE_TITLE
(32769, 343)
ROLE_FAMILY_DESC
(32769, 2358)
ROLE_FAMILY
(32769, 67)
ROLE_CODE
(32769, 343)


In [39]:
from scipy.sparse import hstack
a = hstack(l)


In [41]:
a.reshape

<bound method coo_matrix.reshape of <32769x15627 sparse matrix of type '<type 'numpy.int64'>'
	with 325793 stored elements in COOrdinate format>>

In [42]:
X = a[:, 1:]; y = a[:, 0]

TypeError: 'coo_matrix' object has no attribute '__getitem__'

In [22]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

In [38]:
from scipy.sparse import csr_matrix
csr_matrix.reshape(y, (-1))

NotImplementedError: Reshaping not implemented for csr_matrix.

In [52]:
y1 = y.todense().ravel()

In [59]:
y1 = np.array(y1).ravel()

In [65]:
from sklearn.cross_validation import cross_val_score
cross_val_score(clf, X, y1, scoring=scoring)

[ 0.          0.85466035  1.        ] [ 0.          0.99553007  1.        ]
[ 0.          0.83702532  1.        ] [ 0.          0.99553007  1.        ]
[ 0.          0.86234177  1.        ] [ 0.          0.99514091  1.        ]


array([ 0.57043486,  0.57925238,  0.56639957])

In [64]:
from sklearn import metrics
def scoring(estimator, X, y):
    y_pred = estimator.predict(X)
    fpr, tpr, thresholds = metrics.roc_curve(y, y_pred, pos_label=1)
    print fpr, tpr
    auc = metrics.auc(fpr,tpr)
    return auc

In [68]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size = .7)

In [69]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [72]:
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)

In [81]:
21514./ (21514 + 1198)

0.9472525537160972

In [76]:
confusion_matrix(y_test, y_pred)


array([[  147,  1198],
       [   80, 21514]])

In [77]:
confusion_matrix(y_test, np.ones(y_test.shape))


array([[    0,  1345],
       [    0, 21594]])

In [79]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred)

(array([ 0.64757709,  0.94725255]),
 array([ 0.10929368,  0.99629527]),
 array([ 0.1870229 ,  0.97115515]),
 array([ 1345, 21594]))

In [84]:
from sklearn.metrics import precision_recall_fscore_support
y_ = np.ones(y_test.shape)
y_[0] = 0
precision_recall_fscore_support(y_test, y_, average='binary')

(0.94136367599616355, 0.99995369084004815, 0.96977454414802833, None)

In [88]:
print metrics.precision_score(y_test, y_)
print metrics.recall_score(y_test, y_)

0.941363675996
0.99995369084


In [104]:
print (y_pred[y_test.astype(bool)]).mean()
print (1 - y_pred[~y_test.astype(bool)]).mean()

0.996295267204
0.109293680297


In [103]:
y_pred[~y_test.astype(bool)].mean()

0.89070631970260228

In [115]:
K

TypeError: 'KFold' object is not iterable

In [125]:
X = df.values[:, 1:]
y = df.values[:, 0]
from sklearn.model_selection import KFold
scores = []
kf = KFold()
for tr_ind, test_ind in kf.split(X):
    X_train, X_test = X[tr_ind], X[test_ind]
    y_train, y_test = y[tr_ind], y[test_ind]
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print y_pred, y_test
    scores.append(precision_recall_fscore_support(y_test, y_pred))
    
print scores

[1 1 1 ..., 1 1 1] [1 1 1 ..., 1 1 0]
[1 1 1 ..., 1 1 1] [1 1 1 ..., 1 1 1]
[1 1 1 ..., 1 1 1] [0 1 1 ..., 1 1 1]
[(array([ 0.        ,  0.94305594]), array([ 0.,  1.]), array([ 0.        ,  0.97069355]), array([  622, 10301])), (array([ 0.        ,  0.94278129]), array([ 0.,  1.]), array([ 0.        ,  0.97054804]), array([  625, 10298])), (array([ 0.        ,  0.94049254]), array([ 0.,  1.]), array([ 0.        ,  0.96933384]), array([  650, 10273]))]


In [130]:
df.head()

ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0       1     39353   85475         117961         118300         123472   
1       1     17183    1540         117961         118343         123125   
2       1     36724   14457         118219         118220         117884   
3       1     36135    5396         117961         118343         119993   
4       1     42680    5905         117929         117930         119569   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117905            117906       290919     117908  
1      118536            118536       308574     118539  
2      117879            267952        19721     117880  
3      118321            240983       290919     118322  
4      119323            123932        19793     119325

In [136]:
gb = df.groupby('RESOURCE')
print next(iter(gb))

(0,        ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
3367        1         0      36         117961         118413         119968   
3453        1         0    4468         117961         118413         119968   
4250        1         0    4583         117961         118413         120370   
4354        0         0   71215         117961         118386         118404   
6842        1         0   87908         117961         118413         120370   
10700       1         0   51138         117961         118413         119968   
15425       1         0   87908         117961         118413         120370   
16183       1         0   51138         117961         118413         119968   
17724       1         0    4417         117961         118413         119968   
18669       1         0   72347         117961         118413         120370   
19824       1         0    4468         117961         118413         119968   
25991       1         0    4417     