In [2]:
!head -10 ml-100k/u.data


196	242	3	881250949
186	302	3	891717742
22	377	1	878887116
244	51	2	880606923
166	346	1	886397596
298	474	4	884182806
115	265	2	881171488
253	465	5	891628467
305	451	3	886324817
6	86	3	883603013


In [3]:
import pandas as pd
#ratings = pd.read_csv('ml-1m/ratings.dat', delimiter="::", engine="python", header=None)
ratings = pd.read_csv('ml-100k/u.data', delimiter="\t", engine="python", header=None)

In [4]:
ratings.columns = ["UserID::MovieID::Rating::Timestamp".split("::")]
#ratings = ratings.iloc[:1000, :]
ratings.head()


UserID  MovieID  Rating  Timestamp
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [5]:
ratings.isnull().sum()

UserID       0
MovieID      0
Rating       0
Timestamp    0
dtype: int64

In [6]:
import numpy as np
np.unique(ratings['Rating'])

array([1, 2, 3, 4, 5])

* Do we have any duplicate ratings, i.e., a (userid, movieid) combination that is repeated more than once?

In [7]:
user_movie_pairs = zip(ratings['UserID'].values, ratings['MovieID'].values)

In [8]:
print len(user_movie_pairs), len(set(user_movie_pairs))

100000 100000


In [9]:
print ratings['UserID'].describe()
n_user = len(ratings['UserID'].unique())
print "number of users: %s\n" % n_user
print set(ratings['UserID'].unique()) == set(range(1, n_user + 1))
# User ids are range(1, 6041), i.e., are all values between 1 and 6040
# We can use a simple mapping: user_index=UserID-1


count    100000.00000
mean        462.48475
std         266.61442
min           1.00000
25%         254.00000
50%         447.00000
75%         682.00000
max         943.00000
Name: UserID, dtype: float64
number of users: 943

True


In [64]:
!cat ml-100k/u.info

943 users
1682 items
100000 ratings


In [10]:
#!head ml-1m/movies.dat
!head ml-100k/u.item

1|Toy Story (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)|0|0|0|1|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0
2|GoldenEye (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?GoldenEye%20(1995)|0|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0|1|0|0
3|Four Rooms (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Four%20Rooms%20(1995)|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|1|0|0
4|Get Shorty (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Get%20Shorty%20(1995)|0|1|0|0|0|1|0|0|1|0|0|0|0|0|0|0|0|0|0
5|Copycat (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Copycat%20(1995)|0|0|0|0|0|0|1|0|1|0|0|0|0|0|0|0|1|0|0
6|Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)|01-Jan-1995||http://us.imdb.com/Title?Yao+a+yao+yao+dao+waipo+qiao+(1995)|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|0|0|0|0
7|Twelve Monkeys (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Twelve%20Monkeys%20(1995)|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|1|0|0|0
8|Babe (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Babe%20(1995)|0|0|0|0|1

In [70]:
#movies = pd.read_csv('ml-1m/movies.dat', delimiter='::', engine='python', header=None)
movies = pd.read_csv('ml-100k/u.item', delimiter='|', engine='python', header=None)
#movies.columns = 'MovieID::Title::Genres'.split('::')
columns = ' MovieID | movie title | release date | video release date |' \
              'IMDb URL | unknown | Action | Adventure | Animation |'\
              'Children | Comedy | Crime | Documentary | Drama | Fantasy |'\
              'Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi |'\
              'Thriller | War | Western'.split('|')

movies.columns = ["-".join(i.strip().split()) for i in columns]                
movies.head()

print "The following movie id's are missing from movie table"
print sorted(set(range(1, movies.MovieID.max())) - set(movies.MovieID))
print "\nnumber of unique movies: %s\n" %  len(set(movies.MovieID))

mi = ratings['MovieID'].unique()
mi.sort()
print sorted(set(movies.MovieID) - set(mi))
print len(mi)
# movie id have some missing values in addition to the missing values above
# , i.e., there are movies that are not rated by any user.

#movie_index_to_ID = dict(zip(range(movies.MovieID.unique().shape[0]), movies.MovieID))
movie_index_to_ID = dict(zip(range(len(mi)), mi))
#movie_ID_to_index = dict(zip(movies.MovieID, range(movies.MovieID.unique().shape[0])))
movie_ID_to_index = {k: v for v, k in movie_index_to_ID.iteritems()}


The following movie id's are missing from movie table
[]

number of unique movies: 1682

[]
1682


In [74]:
pp_sim.shape

(1682, 1682)

In [12]:
len(movies.MovieID) == len(movies.MovieID.unique())

True

In [13]:
from scipy.sparse import csr_matrix
row = ratings['MovieID'].values
col = ratings['UserID'].values
data = ratings['Rating'].values
ratings_matrix = csr_matrix((data, (row, col)))



In [14]:
ratings_matrix.shape

(1683, 944)

In [15]:
def trace_dot(X, Y):
    """Trace of np.dot(X, Y.T)."""
    return np.dot(X.ravel(), Y.ravel())
norm_X = np.dot(X.data, X.data)
norm_WH = trace_dot(np.dot(np.dot(W.T, W), H), H)
cross_prod = trace_dot((X * H.T), W)
error = np.sqrt(norm_X + norm_WH - 2. * cross_prod)

NameError: name 'X' is not defined

In [16]:
error/X.shape[0]/X.shape[1]

NameError: name 'error' is not defined

In [17]:
from pyspark import SparkConf, SparkContext
from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .config("spark.some.config.option", "some-value") \
    .getOrCreate()

sc = spark.sparkContext
sc.setLogLevel("WARN")


In [18]:
from pyspark.sql.functions import rand

def kfold_cv_generator(dataset, n_folds=3, seed = None):
    if not seed:
        seed = 0
    h = 1.0 / n_folds
    randCol = "cv_rand"
    df = dataset.select("*", rand(seed).alias(randCol)).cache()
    for i in range(n_folds):
        validateLB = i * h
        validateUB = (i + 1) * h
        condition = (df[randCol] >= validateLB) & (df[randCol] < validateUB)
        validation = df.filter(condition)
        train = df.filter(~condition)
        yield train.drop(randCol), validation.drop(randCol)

In [19]:
#ratings_sp = spark.createDataFrame(ratings)

In [20]:
ratings.columns

Index([u'UserID', u'MovieID', u'Rating', u'Timestamp'], dtype='object')

In [21]:
import os
#TODO: Should use broadcast for movie_ID_to_index?
def parse_data(line):
    fields = line.split("\t")
    user_id = int(fields[0])
    movie_id = int(fields[1])
    rating = float(fields[2])
    ts = fields[3]
    return movie_ID_to_index_bc.value[movie_id], user_id - 1, rating, ts
    
movie_ID_to_index_bc = sc.broadcast(movie_ID_to_index)
#u_data_file = os.path.join("ml-1m", "ratings.dat")
u_data_file = os.path.join("ml-100k", "u.data")
ratings_rdd = sc.textFile(u_data_file).map(parse_data)#.cache().filter(lambda x: x is not None)

In [22]:
x = ratings_rdd.collect()
pd.DataFrame(x).describe()

0             1              2
count  100000.000000  100000.00000  100000.000000
mean      424.530130     461.48475       3.529860
std       330.798356     266.61442       1.125674
min         0.000000       0.00000       1.000000
25%       174.000000     253.00000       3.000000
50%       321.000000     446.00000       4.000000
75%       630.000000     681.00000       4.000000
max      1681.000000     942.00000       5.000000

number of unique movies: 3883
number of users: 6040

In [23]:
ratings_columns = "UserID::MovieID::Rating::Timestamp".split("::")
ratings_sp = spark.createDataFrame(ratings_rdd, schema=ratings_columns)
ratings_sp.columns

['UserID', 'MovieID', 'Rating', 'Timestamp']

In [24]:
import numpy as np
import os
from pyspark.mllib.recommendation import ALS, MatrixFactorizationModel, Rating

#u_data_file = os.path.join("ml-1m", "ratings.dat")
#ratings = sc.textFile(u_data_file).map(parse_data).cache()#.filter(lambda x: x is not None)

#ratings_train = ratings.filter(lambda x: x[3] < 8).map(lambda x: x[:-1])
#ratings_test = ratings.filter(lambda x: x[3] >= 8).map(lambda x: x[:-1])

#print("number of train points: %d" % ratings_train.count())
#print("number of test points: %d" % ratings_test.count())

n_folds = 10
MSE = np.zeros(n_folds)
for i, (ratings_train, ratings_test) in enumerate(kfold_cv_generator(ratings_sp, n_folds)):
    
    print ratings_train.count()
    # TODO: Remove timestamp column from the begining
    model = ALS.train(ratings_train.select(['UserID', 'MovieID', 'Rating']), rank = 10, iterations = 10)

    test_data = ratings_test.rdd.map(lambda r: (r[0], r[1]))
    predictions = model.predictAll(test_data).map(lambda r: ((r[0], r[1]), r[2]))
    p = predictions.collect()
    ratesAndPreds = ratings_test.rdd.map(lambda r: ((r[0], r[1]), r[2])).join(predictions)
    MSE[i] = (ratesAndPreds.map(lambda r: (r[1][0] - r[1][1])**2).mean())**.5

    print("Mean Squared Error = " + str(MSE))


89918
Mean Squared Error = [ 1.06412564  0.          0.          0.          0.          0.          0.
  0.          0.          0.        ]
90035
Mean Squared Error = [ 1.06412564  1.04732351  0.          0.          0.          0.          0.
  0.          0.          0.        ]
90011
Mean Squared Error = [ 1.06412564  1.04732351  1.06404093  0.          0.          0.          0.
  0.          0.          0.        ]
89995
Mean Squared Error = [ 1.06412564  1.04732351  1.06404093  1.05980775  0.          0.          0.
  0.          0.          0.        ]
89999
Mean Squared Error = [ 1.06412564  1.04732351  1.06404093  1.05980775  1.05509787  0.          0.
  0.          0.          0.        ]
90004
Mean Squared Error = [ 1.06412564  1.04732351  1.06404093  1.05980775  1.05509787  1.0639099   0.
  0.          0.          0.        ]
89915
Mean Squared Error = [ 1.06412564  1.04732351  1.06404093  1.05980775  1.05509787  1.0639099
  1.03980106  0.          0.          0.        ]

In [25]:
model = ALS.train(ratings_sp.select(['UserID', 'MovieID', 'Rating']), rank = 10, iterations = 10)

In [26]:
pf = model.productFeatures()
pf_coordinate = pf.map(lambda r: (r[0],  zip(range(len(r[1])), r[1]))).map(lambda r: r[0])

In [27]:
uf = model.userFeatures().collect()

In [28]:
from matplotlib import pyplot as plt

In [29]:
movie_index_list = [i[1] for i in model.recommendProducts(0, 10)]
[movie_index for movie_index_to_ID[movie_index]

SyntaxError: invalid syntax (<ipython-input-29-79f290f9d2d1>, line 2)

### Row-style to coordinate conversion:

In [31]:
"""
m = [
(0, (v00, v01, v02))
(2, (v20, v21, v22))
(5, (v50, v51, v52))
]

=>

[
(0, [(0, v00), (1, v01), (2, v02)])
(2, [(0, v20), (1, v21), (2, v22)])
(5, [(0, v50), (1, v51), (2, v52)])
]

=>

[
(0, 0, v00), (0, 1, v01), (0, 2, v02), 
(2, 0, v20), (2, 1, v21), (2, 2, v22), 

]
"""
def row_style_to_coordinate(m):
    x = m.map(lambda r: (r[0], zip(range(len(r[1])), r[1])))
    return x.flatMap(lambda r: [(r[0], i[0], i[1]) for i in r[1]])

In [32]:
def coordinate_to_sparse(m):
    row, col, data = np.array(m).T
    return csr_matrix((data, (row, col)))


In [88]:
pf_rdd = model.productFeatures()
uf_rdd = model.userFeatures()
user_features = row_style_to_coordinate(pf)
product_features = row_style_to_coordinate(uf)
print coordinate_to_sparse(user_features.collect()).todense().shape
print coordinate_to_sparse(product_features.collect()).todense().shape

(943, 10)
(1682, 10)


In [90]:
pf_sparse = coordinate_to_sparse(product_features.collect())

In [99]:
pf = np.array(pf_sparse.todense())

In [108]:
def array_norm(a):
    return ((a**2).dot(np.ones((a.shape[1], 1))))**0.5

In [176]:
pf.shape

(1682, 10)

In [183]:
from sklearn.preprocessing import normalize
pf_norm = normalize(pf, axis=1)

In [182]:
pf_norm = pf/((pf**2).dot(np.ones((pf_sparse.shape[1], 1))))**0.5

In [184]:
array_norm(pf_norm)

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 1.],
       [ 1.],
       [ 1.]])

In [110]:
pp_sim = np.dot(pf_norm, pf_norm.T)

In [118]:
np.argsort(pp_sim[0, :])

array([1335, 1597,  986, ...,  203,   94,    0])

In [149]:
recom_movie_index = np.argsort(pp_sim[0, :])[::-1][:10]

In [150]:
recom_movie_index

array([  0,  94, 203, 209, 676, 598, 710, 193, 434, 658])

In [85]:
movies[(movies.Horror == 1) & (movies['Sci-Fi'] == 1)].head()

MovieID                                     movie-title release-date  \
83        84  Robert A. Heinlein's The Puppet Masters (1994)  01-Jan-1994   
100      101                              Heavy Metal (1981)  08-Mar-1981   
182      183                                    Alien (1979)  01-Jan-1979   
183      184                         Army of Darkness (1993)  01-Jan-1993   
342      343                      Alien: Resurrection (1997)  01-Jan-1997   

     video-release-date                                           IMDb-URL  \
83                  NaN  http://us.imdb.com/M/title-exact?Robert%20A.%2...   
100                 NaN  http://us.imdb.com/M/title-exact?Heavy%20Metal...   
182                 NaN    http://us.imdb.com/M/title-exact?Alien%20(1979)   
183                 NaN  http://us.imdb.com/M/title-exact?Army%20of%20D...   
342                 NaN  http://us.imdb.com/M/title-exact?Alien%3A+Resu...   

     unknown  Action  Adventure  Animation  Children   ...     Fantasy  \
83         0       0          0          0         0   ...           0   
100        0       1          1          1         0   ...           0   
182        0       1          0          0         0   ...           0   
183        0       1          1          0         0   ...           0   
342        0       1          0          0         0   ...           0   

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
83           0       1        0        0        0       1         0    0   
100          0       1        0        0        0       1         0    0   
182          0       1        0        0        0       1         1    0   
183          0       1        0        0        0       1         0    0   
342          0       1        0        0        0       1         0    0   

     Western  
83         0  
100        0  
182        0  
183        0  
342        0  

[5 rows x 24 columns]

In [129]:
pp_sim[182, 0]

0.77456068242879184

In [122]:
movies.head()

MovieID        movie-title release-date  video-release-date  \
0        1   Toy Story (1995)  01-Jan-1995                 NaN   
1        2   GoldenEye (1995)  01-Jan-1995                 NaN   
2        3  Four Rooms (1995)  01-Jan-1995                 NaN   
3        4  Get Shorty (1995)  01-Jan-1995                 NaN   
4        5     Copycat (1995)  01-Jan-1995                 NaN   

                                            IMDb-URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Children   ...     Fantasy  Film-Noir  Horror  \
0          0          1         1   ...           0          0       0   
1          1          0         0   ...           0          0       0   
2          0          0         0   ...           0          0       0   
3          0          0         0   ...           0          0       0   
4          0          0         0   ...           0          0       0   

   Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0        0       0         0    0        0  
1        0        0        0       0         1    0        0  
2        0        0        0       0         1    0        0  
3        0        0        0       0         0    0        0  
4        0        0        0       0         1    0        0  

[5 rows x 24 columns]

In [151]:
[movies[movies.MovieID == movie_index_to_ID[i]]['movie-title'].tolist()[0] for i in recom_movie_index]

['Toy Story (1995)',
 'Aladdin (1992)',
 'Back to the Future (1985)',
 'Indiana Jones and the Last Crusade (1989)',
 'Fire on the Mountain (1996)',
 'Police Story 4: Project S (Chao ji ji hua) (1993)',
 'Substance of Fire, The (1996)',
 'Sting, The (1973)',
 'Butch Cassidy and the Sundance Kid (1969)',
 'Arsenic and Old Lace (1944)']

In [152]:
recom_movie_index

array([  0,  94, 203, 209, 676, 598, 710, 193, 434, 658])

In [231]:
recom_movie_index

array([1642, 1462, 1119, 1153, 1285])

In [42]:
#help(pd.DataFrame({'MovieID':[movie_index_to_ID[i] for i in recom_movie_index]}).join)

In [43]:
(pd.DataFrame({'MovieID':[movie_index_to_ID[i] for i in recom_movie_index]})).join

<bound method DataFrame.join of    MovieID
0      718
1      361
2     1643
3     1375
4     1218>

In [189]:
pd.merge(pd.DataFrame({'MovieID':[movie_index_to_ID[i] for i in recom_movie_index]}), movies, how='outer', on='MovieID', suffixes=('_x', '_y'))

MovieID                                        movie-title release-date  \
0           1                                   Toy Story (1995)  01-Jan-1995   
1          95                                     Aladdin (1992)  01-Jan-1992   
2         204                          Back to the Future (1985)  01-Jan-1985   
3         210          Indiana Jones and the Last Crusade (1989)  01-Jan-1989   
4         677                        Fire on the Mountain (1996)  24-Jan-1997   
5         599  Police Story 4: Project S (Chao ji ji hua) (1993)  16-Aug-1996   
6         711                      Substance of Fire, The (1996)  06-Dec-1996   
7         194                                  Sting, The (1973)  01-Jan-1973   
8         435          Butch Cassidy and the Sundance Kid (1969)  01-Jan-1969   
9         659                        Arsenic and Old Lace (1944)  01-Jan-1944   
10          2                                   GoldenEye (1995)  01-Jan-1995   
11          3                                  Four Rooms (1995)  01-Jan-1995   
12          4                                  Get Shorty (1995)  01-Jan-1995   
13          5                                     Copycat (1995)  01-Jan-1995   
14          6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...  01-Jan-1995   
15          7                              Twelve Monkeys (1995)  01-Jan-1995   
16          8                                        Babe (1995)  01-Jan-1995   
17          9                            Dead Man Walking (1995)  01-Jan-1995   
18         10                                 Richard III (1995)  22-Jan-1996   
19         11                               Seven (Se7en) (1995)  01-Jan-1995   
20         12                         Usual Suspects, The (1995)  14-Aug-1995   
21         13                            Mighty Aphrodite (1995)  30-Oct-1995   
22         14                                 Postino, Il (1994)  01-Jan-1994   
23         15                          Mr. Holland's Opus (1995)  29-Jan-1996   
24         16                 French Twist (Gazon maudit) (1995)  01-Jan-1995   
25         17                         From Dusk Till Dawn (1996)  05-Feb-1996   
26         18                          White Balloon, The (1995)  01-Jan-1995   
27         19                              Antonia's Line (1995)  01-Jan-1995   
28         20                          Angels and Insects (1995)  01-Jan-1995   
29         21                      Muppet Treasure Island (1996)  16-Feb-1996   
...       ...                                                ...          ...   
1652     1653  Entertaining Angels: The Dorothy Day Story (1996)  27-Sep-1996   
1653     1654                       Chairman of the Board (1998)  01-Jan-1998   
1654     1655                                  Favor, The (1994)  01-Jan-1994   
1655     1656                                 Little City (1998)  20-Feb-1998   
1656     1657                                      Target (1995)  28-Feb-1996   
1657     1658                      Substance of Fire, The (1996)  06-Dec-1996   
1658     1659                    Getting Away With Murder (1996)  12-Apr-1996   
1659     1660                                 Small Faces (1995)  09-Aug-1996   
1660     1661                                New Age, The (1994)  01-Jan-1994   
1661     1662                                 Rough Magic (1995)  30-May-1997   
1662     1663                            Nothing Personal (1995)  30-Apr-1997   
1663     1664                     8 Heads in a Duffel Bag (1997)  18-Apr-1997   
1664     1665                           Brother's Kiss, A (1997)  25-Apr-1997   
1665     1666                                        Ripe (1996)  02-May-1997   
1666     1667                              Next Step, The (1995)  13-Jun-1997   
1667     1668                          Wedding Bell Blues (1996)  13-Jun-1997   
1668     1669                           MURDER and murder (1996)  20-Jun-1997   
1669     1670                        

In [46]:
pd.DataFrame({'MovieID':[movie_index_to_ID[i] for i in recom_movie_index]}).join

<bound method DataFrame.join of    MovieID
0      718
1      361
2     1643
3     1375
4     1218>

In [154]:
[movies['movie-title'].loc[movie_index_to_ID[i]] for i in recom_movie_index]

['GoldenEye (1995)',
 'Terminator 2: Judgment Day (1991)',
 'Patton (1970)',
 'M*A*S*H (1970)',
 'Volcano (1997)',
 "Daniel Defoe's Robinson Crusoe (1996)",
 'Tin Men (1987)',
 'Terminator, The (1984)',
 'American Werewolf in London, An (1981)',
 'Fried Green Tomatoes (1991)']

In [156]:
movies.loc[recom_movie_index]

MovieID                                        movie-title release-date  \
0          1                                   Toy Story (1995)  01-Jan-1995   
94        95                                     Aladdin (1992)  01-Jan-1992   
203      204                          Back to the Future (1985)  01-Jan-1985   
209      210          Indiana Jones and the Last Crusade (1989)  01-Jan-1989   
676      677                        Fire on the Mountain (1996)  24-Jan-1997   
598      599  Police Story 4: Project S (Chao ji ji hua) (1993)  16-Aug-1996   
710      711                      Substance of Fire, The (1996)  06-Dec-1996   
193      194                                  Sting, The (1973)  01-Jan-1973   
434      435          Butch Cassidy and the Sundance Kid (1969)  01-Jan-1969   
658      659                        Arsenic and Old Lace (1944)  01-Jan-1944   

     video-release-date                                           IMDb-URL  \
0                   NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
94                  NaN  http://us.imdb.com/M/title-exact?Aladdin%20(1992)   
203                 NaN  http://us.imdb.com/M/title-exact?Back%20to%20t...   
209                 NaN  http://us.imdb.com/M/title-exact?Indiana%20Jon...   
676                 NaN  http://us.imdb.com/M/title-exact?Fire%20on%20t...   
598                 NaN  http://us.imdb.com/M/title-exact?Project%20S%2...   
710                 NaN  http://us.imdb.com/M/title-exact?Substance%20o...   
193                 NaN  http://us.imdb.com/M/title-exact?Sting,%20The%...   
434                 NaN  http://us.imdb.com/M/title-exact?Butch%20Cassi...   
658                 NaN  http://us.imdb.com/M/title-exact?Arsenic%20and...   

     unknown  Action  Adventure  Animation  Children   ...     Fantasy  \
0          0       0          0          1         1   ...           0   
94         0       0          0          1         1   ...           0   
203        0       0          0          0         0   ...           0   
209        0       1          1          0         0   ...           0   
676        0       0          0          0         0   ...           0   
598        0       1          0          0         0   ...           0   
710        0       0          0          0         0   ...           0   
193        0       0          0          0         0   ...           0   
434        0       1          0          0         0   ...           0   
658        0       0          0          0         0   ...           0   

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0            0       0        0        0        0       0         0    0   
94           0       0        1        0        0       0         0    0   
203          0       0        0        0        0       1         0    0   
209          0       0        0        0        0       0         0    0   
676          0       0        0        0        0       0         0    0   
598          0       0        0        0        0       0         0    0   
710          0       0        0        0        0       0         0    0   
193          0       0        0        0        0       0         0    0   
434          0       0        0        0        0       0         0    0   
658          0       0        0        1        0       0         1    0   

     Western  
0          0  
94         0  
203        0  
209        0  
676        0  
598        0  
710        0  
193        0  
434        1  
658        0  

[10 rows x 24 columns]

In [165]:
np.save('pp_sim', pp_sim)

In [169]:
!ls -lh pp_sim.npy

-rw-r--r-- 1 amir amir 22M Jun 19 23:51 pp_sim.npy


In [167]:
np.load('pp_sim.npy')

array([[ 1.        ,  0.92481848,  0.48541687, ...,  0.60664059,
         0.83372547,  0.81725406],
       [ 0.92481848,  1.        ,  0.45560719, ...,  0.61020387,
         0.74548876,  0.75759856],
       [ 0.48541687,  0.45560719,  1.        , ...,  0.61748687,
         0.20788478,  0.45697249],
       ..., 
       [ 0.60664059,  0.61020387,  0.61748687, ...,  1.        ,
         0.58217721,  0.84315998],
       [ 0.83372547,  0.74548876,  0.20788478, ...,  0.58217721,
         1.        ,  0.78128874],
       [ 0.81725406,  0.75759856,  0.45697249, ...,  0.84315998,
         0.78128874,  1.        ]])

In [190]:
def get_movie_image(url):
    return Image(url=get_poster(url, base_url, api_key))

In [59]:
get_poster(movie_list[1], base_url, api_key)

u'http://image.tmdb.org/t/p/w185/1oqfg2IBGNFAFylDK56NXo558y2.jpg'

In [276]:
s = ''
for url in movie_list:
    s += '<img src="%s" >' % get_poster_imdb(url)

In [277]:
s

'<img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SY500_SX335_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BNTI4ODQ1MzAzNV5BMl5BanBnXkFtZTgwMzU4NzMxMDE@._V1_SY250_CR0,0,187,250_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_CR0,0,321,500_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY500_CR0,0,339,500_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1OTk5MjQyM15BMl5BanBnXkFtZTcwOTM5NzEyMQ@@._V1_SX165_CR0,0,165,237_AL_.jpg" ><img src="" ><img src="" ><img src="" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMTkyMTM2NDk5Nl5BMl5BanBnXkFtZTgwNzY1NzEyMDE@._V1_SY500_CR0,0,337,500_AL_.jpg" ><img src="https://im

In [160]:
s

u'<img src="http://image.tmdb.org/t/p/w185/uMZqKhT4YA6mqo2yczoznv7IDmv.jpg" ><img src="http://image.tmdb.org/t/p/w185/qsHpmqekgeQKMKL8PWnFsrXTXGs.jpg" ><img src="http://image.tmdb.org/t/p/w185/pTpxQB1N0waaSc3OSn0e9oc8kx9.jpg" ><img src="http://image.tmdb.org/t/p/w185/g8qWglC2XXCIN8P51eCljFvCNNJ.jpg" ><img src="" ><img src="http://image.tmdb.org/t/p/w185/7pgS6qYWtSiJpEJW3YQJqD6EVRG.jpg" ><img src="http://image.tmdb.org/t/p/w185/uXMTgqPIJwLnzcDdIvvD5OUqX8x.jpg" ><img src="http://image.tmdb.org/t/p/w185/mQaM8fDQdFWwCTFp0TZG8fChlZ5.jpg" ><img src="http://image.tmdb.org/t/p/w185/jQH0mTzQ1gQ56H8a0z52WreiEok.jpg" ><img src="http://image.tmdb.org/t/p/w185/jfNhx7ATKNvblvbb7wsfm4YpPaR.jpg" >'

<img src="http://image.tmdb.org/t/p/w185/uMZqKhT4YA6mqo2yczoznv7IDmv.jpg" ><img src="http://image.tmdb.org/t/p/w185/qsHpmqekgeQKMKL8PWnFsrXTXGs.jpg" ><img src="http://image.tmdb.org/t/p/w185/pTpxQB1N0waaSc3OSn0e9oc8kx9.jpg" ><img src="http://image.tmdb.org/t/p/w185/g8qWglC2XXCIN8P51eCljFvCNNJ.jpg" ><img src="" ><img src="http://image.tmdb.org/t/p/w185/7pgS6qYWtSiJpEJW3YQJqD6EVRG.jpg" ><img src="http://image.tmdb.org/t/p/w185/uXMTgqPIJwLnzcDdIvvD5OUqX8x.jpg" ><img src="http://image.tmdb.org/t/p/w185/mQaM8fDQdFWwCTFp0TZG8fChlZ5.jpg" ><img src="http://image.tmdb.org/t/p/w185/jQH0mTzQ1gQ56H8a0z52WreiEok.jpg" ><img src="http://image.tmdb.org/t/p/w185/jfNhx7ATKNvblvbb7wsfm4YpPaR.jpg" >'


'<img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SY500_SX335_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BNTI4ODQ1MzAzNV5BMl5BanBnXkFtZTgwMzU4NzMxMDE@._V1_SY250_CR0,0,187,250_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_CR0,0,321,500_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY500_CR0,0,339,500_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1OTk5MjQyM15BMl5BanBnXkFtZTcwOTM5NzEyMQ@@._V1_SX165_CR0,0,165,237_AL_.jpg" ><img src="" ><img src="" ><img src="" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BMTkyMTM2NDk5Nl5BMl5BanBnXkFtZTgwNzY1NzEyMDE@._V1_SY500_CR0,0,337,500_AL_.jpg" ><img src="https://images-na.ssl-images-amazon.com/images/M/MV5BZDVlNTBjMjctNjAzNS00ZGJhLTg2NzMtNzIwYTIzYTBiMDkyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY500_CR0,0,332,500_AL_.jpg" >'


### Get Movie Posters

In [266]:
import requests
resp = requests.get('http://www.imdb.com/title/tt0114709/?ref_=nv_sr_1')
from bs4 import BeautifulSoup
bs = BeautifulSoup(resp.content, "lxml")

In [267]:
url

'http://www.imdb.com//title/tt0114709/mediaviewer/rm3813007616?ref_=tt_ov_i'

In [268]:
base_url = 'http://www.imdb.com/'
url = base_url + bs.find("div", class_="poster").a['href']
resp = requests.get(url)
bs = BeautifulSoup(resp.content, 'lxml')


In [269]:
#<div class="pswp__zoom-wrap" style="transform: translate3d(727px, 0px, 0px) scale(1);"><img class="pswp__img pswp__img--placeholder" src="https://images-na.ssl-images-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SY500_SX335_AL_.jpg" style="width: 594px; height: 887px; display: none;"><img class="pswp__img" src="https://images-na.ssl-images-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SY1000_SX670_AL_.jpg" style="display: block; width: 291px; height: 435px;"></div>
image_url = bs.find('meta', itemprop='image')['content']

In [275]:
def get_poster_imdb(url):
    try:
        resp = requests.get(url)
        bs = BeautifulSoup(resp.content, "lxml")
        base_url = 'http://www.imdb.com/'
        url = base_url + bs.find("div", class_="poster").a['href']
        resp = requests.get(url)
        bs = BeautifulSoup(resp.content, 'lxml')
        return bs.find('meta', itemprop='image')['content']
    except:
        return ""

In [271]:
Image(url=image_url)

In [54]:

import requests
import json

response = requests.get('http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)')
print response.url.split('/')[-2]

tt0114709


In [55]:

# Build function to query themoviedb.org's API

# Get base url filepath structure. w185 corresponds to size of movie poster.
api_key = '2554c0fd4b04956e926253a3337c3252'
headers = {'Accept': 'application/json'}
payload = {'api_key': api_key} 
response = requests.get("http://api.themoviedb.org/3/configuration",\
                        params=payload,\
                        headers=headers)
response = json.loads(response.text)
base_url = response['images']['base_url'] + 'w185'

def get_poster(imdb_url, base_url, api_key):
    # Get IMDB movie ID
    response = requests.get(imdb_url)
    movie_id = response.url.split('/')[-2]
    
    # Query themoviedb.org API for movie poster path.
    movie_url = 'http://api.themoviedb.org/3/movie/{:}/images'.format(movie_id)
    headers = {'Accept': 'application/json'}
    payload = {'api_key': api_key} 
    response = requests.get(movie_url, params=payload, headers=headers)
    try:
        file_path = json.loads(response.text)['posters'][0]['file_path']
    except:
        # IMDB movie ID is sometimes no good. Need to get correct one.
        movie_title = imdb_url.split('?')[-1].split('(')[0]
        payload['query'] = movie_title
        response = requests.get('http://api.themoviedb.org/3/search/movie',\
                                params=payload,\
                                headers=headers)
        try:
            movie_id = json.loads(response.text)['results'][0]['id']
            payload.pop('query', None)
            movie_url = 'http://api.themoviedb.org/3/movie/{:}/images'\
                        .format(movie_id)
            response = requests.get(movie_url, params=payload, headers=headers)
            file_path = json.loads(response.text)['posters'][0]['file_path']
        except:
            # Sometimes the url just doesn't work.
            # Return '' so that it does not mess up Image()
            return ''
        
    return base_url + file_path



In [58]:
get_poster(toy_story, base_url, api_key)

u'http://image.tmdb.org/t/p/w185/uMZqKhT4YA6mqo2yczoznv7IDmv.jpg'

In [57]:
from IPython.display import Image
from IPython.display import display

toy_story = 'http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)'
Image(url=get_poster(toy_story, base_url, api_key))

<img src="http://image.tmdb.org/t/p/w185/uMZqKhT4YA6mqo2yczoznv7IDmv.jpg">

In [162]:
product_features_T = product_features.map(lambda r: (r[1], r[0], r[2]))
pp_sim_rdd = matrix_multiply(product_features, product_features_T)
pp_sim = pp_sim_rdd.collect()

KeyboardInterrupt: 

In [1]:
def matrix_multiply(x, y):
    def left_mapper(r):
        i, j, v = r
        return j, (i, v)
    def right_mapper(r):
        j, k, w = r
        return j, (k, w)
    def product_mapper(r):
        _, ((i, v), (k, w)) = r
        return (i, k), v * w
    
    x = x.map(left_mapper)
    y = y.map(right_mapper)
    
    return x.join(y).map(product_mapper).reduceByKey(lambda x, y: x + y).map(lambda r: r[0][0], r[0][1], r[1])

In [21]:
l = [(0, 0, 3.0), (2, 0, -5.0), (3, 2, 1.0),
   (4, 1, 6.0), (6, 2, 2.0), (8, 1, 4.0)]
row = [i[0] for i in l]
col = [i[1] for i in l]
data = [i[2] for i in l]

row, col, data = np.array(l).T
from scipy.sparse import csr_matrix
m1 = csr_matrix((data, (row, col)))


In [22]:
m1.todense()

matrix([[ 3.,  0.,  0.],
        [ 0.,  0.,  0.],
        [-5.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  6.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  2.],
        [ 0.,  0.,  0.],
        [ 0.,  4.,  0.]])

In [13]:
m1.T

<3x9 sparse matrix of type '<type 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Column format>

In [20]:
import numpy as np
np.dot(m1.todense(), m1.todense().T)

matrix([[  9.,   0., -15.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [-15.,   0.,  25.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   1.,   0.,   0.,   2.,   0.,   0.],
        [  0.,   0.,   0.,   0.,  36.,   0.,   0.,   0.,  24.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   2.,   0.,   0.,   4.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,  24.,   0.,   0.,   0.,  16.]])

In [4]:
mat = sc.parallelize([
   (0, 0, 3.0), (2, 0, -5.0), (3, 2, 1.0),
   (4, 1, 6.0), (6, 2, 2.0), (8, 1, 4.0)]
)

In [17]:
mat_t = sc.parallelize([(j, i, v) for i, j, v in l])

In [26]:
matrix_multiply(mat, mat_t).collect()

[((2, 0), -15.0),
 ((6, 3), 2.0),
 ((0, 0), 9.0),
 ((4, 4), 36.0),
 ((8, 8), 16.0),
 ((0, 2), -15.0),
 ((3, 3), 1.0),
 ((4, 8), 24.0),
 ((8, 4), 24.0),
 ((6, 6), 4.0),
 ((2, 2), 25.0),
 ((3, 6), 2.0)]

In [ ]:
number of unique movies: 3883
number of users: 6040

In [68]:
set(x) == set(range(6040))

True

In [69]:
set(y) == set(range(3706))

True

In [66]:
x = [i[0] for i in pf]

In [67]:
y = [i[0] for i in uf]

In [ ]:
pd.DataFrame(x).describe()

In [ ]:
max(sorted(y))

In [ ]:
pd.DataFrame(y).describe()

In [ ]:
plt.plot(sorted(x), '.')
plt.show()

In [ ]:
dir(model)

In [ ]:
np.mean([i[1] for i in p])

In [ ]:
from pyspark.ml.tuning import CrossValidator
from pyspark.ml import Pipeline
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.feature import HashingTF, Tokenizer
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder



lr = LogisticRegression(maxIter=10)

paramGrid = ParamGridBuilder() \
    .addGrid(lr.regParam, np.logspace(-2, 2, 5)) \
    .build()

cnt = 0

class Evaluator:
    def evaluate(self, dataset):
        global cnt
        cnt += 1
        print dataset.count()
        print cnt
        #print dataset['features'].collect()
        #print dataset['label']
        print
        return 1
    
crossval = CrossValidator(estimator=lr,
                          estimatorParamMaps=paramGrid,
                          #evaluator=BinaryClassificationEvaluator(),
                          evaluator=Evaluator(),
                          numFolds=3)  # use 3+ folds in practice

# Run cross-validation, and choose the best set of parameters.
cvModel = crossval.fit(training)



In [ ]:
import os
spark_home = os.environ['SPARK_HOME']
training = spark.read.format("libsvm").load(os.path.join(spark_home, "data/mllib/sample_libsvm_data.txt"))


In [ ]:
training